<?php

declare(strict_types=1);

return [
    'api' => [
        'confirm_delete' => 'Are you sure you want to proceed? This can not be undone.',
        'copied' => 'Copied',
        'copy' => 'Copy',
        'count' => ':count API key(s) created',
        'create_success' => 'API Key created successfully',
        'description' => 'API keys are like secret passwords that allow other tools or apps to connect securely to your account.',
        'empty' => 'No API keys created',
        'label' => 'Label for the API key',
        'new' => 'New API key',
        'private_description' => 'Each API key is unique to you. Treat them like private passwords—don’t share them with anyone you don’t trust.',
        'title' => 'Personal API Keys',
        'warning' => 'Please copy your API key now. For security reasons, it won\'t be shown again.',
    ],
    'auto_delete' => [
        'description' => 'Automatically delete the account and all the data after 6 months of inactivity. Please be certain.',
        'label' => 'Delete my account after 6 months of inactivity',
        'title' => 'Auto delete account',
    ],
    'password' => [
        'confirm' => 'Confirm new password',
        'current' => 'Current password',
        'minimum' => 'Minimum 8 characters.',
        'new' => 'New password',
        'title' => 'Change password',
    ],
    'two_factor' => [
        'authenticator_app' => 'Authenticator app',
        'code_description' => 'Enter the code generated by your authenticator app below.',
        'configured' => 'Configured',
        'confirm_remove' => 'Are you absolutely sure? This action cannot be undone.',
        'description' => 'Use an authentication app to get two-factor authentication codes when prompted.',
        'recovery_codes_description' => 'Use these codes to access your account if you lose access to your authenticator app.',
        'recovery_codes' => 'Recovery codes',
        'scan_description' => 'Use any authenticator app to scan your QR code, or manually use the setup key.',
        'set_up' => 'Set up',
        'setup_key' => 'Setup key:',
        'token_label' => 'Enter 6-digit OTP token',
    ],
    'title' => 'Security and access',
];
