<?php

declare(strict_types=1);
use App\Models\Item;
use App\Models\ItemPhoto;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;

uses(RefreshDatabase::class);

it('belongs to an item', function () {
    $item = Item::factory()->create();
    $photo = ItemPhoto::factory()->create(['item_id' => $item->id]);

    expect($photo->item)->toBeInstanceOf(Item::class);
    expect($photo->item->id)->toBe($item->id);
});

it('encrypts the filename at rest', function () {
    $photo = ItemPhoto::factory()->create(['filename' => 'central-perk.jpg']);

    $rawFilename = DB::table('item_photos')->where('id', $photo->id)->value('filename');

    $this->assertNotSame('central-perk.jpg', $rawFilename);
    expect(decrypt($rawFilename, false))->toBe('central-perk.jpg');
    expect($photo->fresh()->filename)->toBe('central-perk.jpg');
});

it('does not encrypt the path, since it is generated by the application', function () {
    $photo = ItemPhoto::factory()->create(['path' => 'items/1/joey.jpg']);

    $rawPath = DB::table('item_photos')->where('id', $photo->id)->value('path');

    expect($rawPath)->toBe('items/1/joey.jpg');
});

it('casts is_main to a boolean', function () {
    $photo = ItemPhoto::factory()->create(['is_main' => true]);

    expect($photo->fresh()->is_main)->toBeTrue();
});

it('gets the photos of an item ordered by position', function () {
    $item = Item::factory()->create();
    $monica = ItemPhoto::factory()->create(['item_id' => $item->id, 'position' => 3, 'filename' => 'monica.jpg']);
    $rachel = ItemPhoto::factory()->create(['item_id' => $item->id, 'position' => 1, 'filename' => 'rachel.jpg']);
    $phoebe = ItemPhoto::factory()->create(['item_id' => $item->id, 'position' => 2, 'filename' => 'phoebe.jpg']);

    expect($item->photos()->pluck('id')->all())->toBe([$rachel->id, $phoebe->id, $monica->id]);
});

it('gets the main photo of an item', function () {
    $item = Item::factory()->create();
    ItemPhoto::factory()->create(['item_id' => $item->id, 'position' => 1, 'is_main' => false]);
    $chandler = ItemPhoto::factory()->create(['item_id' => $item->id, 'position' => 2, 'is_main' => true]);

    expect($item->mainPhoto)->toBeInstanceOf(ItemPhoto::class);
    expect($item->mainPhoto->id)->toBe($chandler->id);
});

it('has no main photo when the item has no photo', function () {
    $item = Item::factory()->create();

    expect($item->mainPhoto)->toBeNull();
});
