<x-form :action="route('profile.security.2fa.create')" method="post" id="authenticator-app" x-target="authenticator-app notifications" x-target.back="authenticator-app" class="border-b border-hairline p-4">
  <div class="flex flex-col gap-y-4">
    <p class="text-body">
      <span class="inline-flex h-6 w-6 items-center justify-center rounded-full border border-hairline text-sm text-ink">1</span>
      {{ __('Use any authenticator app to scan your QR code, or manually use the setup key.') }}
    </p>
    <div class="mx-auto w-full">
      <div class="mb-2 flex h-36 w-36 items-center justify-center rounded-lg border border-hairline bg-white">{!! $qrCodeSvg !!}</div>
      <p class="mb-4 text-sm text-body">
        {{ __('Setup key:') }}
        <code>{{ $secret }}</code>
      </p>
    </div>
  </div>
  <div
    class="flex flex-col gap-y-4"
    x-data="{
      digits: ['', '', '', '', '', ''],
      handleInput(index, event) {
        const value = event.target.value
        if (value.length > 0 && /^[0-9]$/.test(value)) {
          this.digits[index] = value
          this.updateToken()
          if (index < 5) {
            this.$refs['digit' + (index + 1)].focus()
          }
        }
      },
      handleKeydown(index, event) {
        if (event.key === 'Backspace' && this.digits[index] === '' && index > 0) {
          this.$refs['digit' + (index - 1)].focus()
        }
      },
      handlePaste(event) {
        event.preventDefault()
        const paste = event.clipboardData
          .getData('text')
          .replace(/\D/g, '')
          .slice(0, 6)
        for (let i = 0; i < paste.length; i++) {
          this.digits[i] = paste[i]
        }
        this.updateToken()
        if (paste.length === 6) {
          this.$refs['digit5'].focus()
        } else if (paste.length > 0) {
          this.$refs['digit' + (paste.length - 1)].focus()
        }
      },
      updateToken() {
        this.$refs.tokenInput.value = this.digits.join('')
      },
    }">
    <p class="text-body">
      <span class="inline-flex h-6 w-6 items-center justify-center rounded-full border border-hairline text-sm text-ink">2</span>
      {{ __('Enter the code generated by your authenticator app below.') }}
    </p>
    <div class="mb-4">
      <label class="mb-2 block text-sm font-medium text-ink">
        {{ __('Enter 6-digit OTP token') }}
      </label>
      <div class="flex gap-2">
        @for ($i = 0; $i < 6; $i++)
          <input type="text" x-ref="digit{{ $i }}" x-model="digits[{{ $i }}]" @input="handleInput({{ $i }}, $event)" @keydown="handleKeydown({{ $i }}, $event)" @paste="handlePaste($event)" maxlength="1" inputmode="numeric" pattern="[0-9]" {{ $i === 0 ? 'autofocus' : '' }} required class="h-12 w-12 rounded-md border border-hairline bg-input text-center text-lg font-semibold text-ink focus:border-brand focus:ring-2 focus:ring-brand focus:outline-none" />
        @endfor
      </div>
      <input type="hidden" name="token" x-ref="tokenInput" required />
      @if ($errors->has('token'))
        <p class="mt-2 text-sm text-error">{{ $errors->first('token') }}</p>
      @endif
    </div>
  </div>
  <div class="flex justify-between">
    <x-button.secondary href="{{ route('profile.security.index') }}" x-target="authenticator-app">
      {{ __('Cancel') }}
    </x-button.secondary>

    <x-button>
      {{ __('Save') }}
    </x-button>
  </div>
</x-form>
