<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('item_photos', function (Blueprint $table): void {
            $table->id()->comment('primary key');
            $table->unsignedBigInteger('item_id')->comment('item the photo belongs to');
            $table->string('path')->comment('path of the file on the disk, generated by the application, never user supplied');
            $table->text('filename')->comment('original name of the uploaded file, as given by the user');
            $table->string('mime_type')->comment('mime type of the file, e.g. image/jpeg');
            $table->unsignedInteger('size')->comment('size of the file in bytes');
            $table->boolean('is_main')->default(false)->comment('true when the photo is the main visual of the item, and only one photo per item can be');
            $table->unsignedInteger('position')->comment('order of the photo within the item, starting at 1');
            $table->unsignedBigInteger('created_by_id')->nullable()->comment('user who added the photo');
            $table->text('created_by_name')->nullable()->comment('name of the creator at the time');
            $table->unsignedBigInteger('updated_by_id')->nullable()->comment('user who last updated the photo');
            $table->text('updated_by_name')->nullable()->comment('name of the last editor at the time');
            $table->timestamps();

            // A photo row maps to a real file on the disk, so deletes are hard:
            // the file is removed along with the row.
            $table->foreign('item_id')->references('id')->on('items')->cascadeOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('item_photos');
    }
};
